version: 2.1
orbs:
  node: circleci/node@5.0.3
workflows:
  sample: # This is the name workflow, feel free to change it to better match you workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - node/test:
          version: '16.13.2'
          pkg-manager: npm
