version: 2.1

jobs:
  test:
    executor:
      name: node/default
      tag: '16.13.2'
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            if [[ ! -z $CIRCLE_PULL_REQUEST ]] ; then
              npm run test
            fi



